CREATE TABLE IF NOT EXISTS user
(
    id  VARCHAR(255) PRIMARY KEY,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS last_location
(
    id    VARCHAR(255) PRIMARY KEY,
    x     FLOAT       DEFAULT 0,
    y     FLOAT       DEFAULT 0,
    FOREIGN KEY (id) REFERENCES user (id)
);